language: go
go:
 - 1.8

sudo: false

# Use trusty for postgres 9.5 support
dist: trusty

addons:
  postgresql: "9.5"

services:
  - postgresql

install:
 - go get github.com/constabulary/gb/...
 - go get github.com/golang/lint/golint
 - go get github.com/fzipp/gocyclo

script:
 - ./travis-install-kafka.sh
 - ./travis-test.sh

notifications:
    webhooks:
        urls:
            - "https://scalar.vector.im/api/neb/services/hooks/dHJhdmlzLWNpLyU0MGtlZ2FuJTNBbWF0cml4Lm9yZy8lMjFhWmthbkFuV0VkeGNSSVFrV24lM0FtYXRyaXgub3Jn"
        on_success: change  # always|never|change
        on_failure: always
        on_start: never

