language: go
go:
 - 1.8

sudo: false

# Use trusty for postgres 9.5 support
dist: trusty

addons:
  apt:
    packages:
    - openssl
  postgresql: "9.5"

services:
  - postgresql

install:
 - go get github.com/constabulary/gb/...
 - go get github.com/client9/misspell/...
 - go get github.com/alecthomas/gometalinter

# Generate a self-signed X.509 certificate for TLS.
before_script:
 - openssl req -x509 -newkey rsa:4096 -keyout server.key -out server.crt -days 365 -nodes -subj /CN=localhost

script:
 - ./travis-install-kafka.sh
 - ./travis-test.sh

notifications:
    webhooks:
        urls:
            - "https://scalar.vector.im/api/neb/services/hooks/dHJhdmlzLWNpLyU0MGtlZ2FuJTNBbWF0cml4Lm9yZy8lMjFhWmthbkFuV0VkeGNSSVFrV24lM0FtYXRyaXgub3Jn"
        on_success: change  # always|never|change
        on_failure: always
        on_start: never
