language: go

go_import_path: github.com/matrix-org/dendrite

go:
 - 1.11.x
 - 1.12.x

env:
- TEST_SUITE="lint"
- TEST_SUITE="unit-test"
- TEST_SUITE="integ-test"

sudo: false

# Use trusty for postgres 9.5 support
dist: trusty

addons:
  postgresql: "9.5"

services:
  - postgresql

cache:
  directories:
    - .downloads

script:
 - ./scripts/travis-test.sh

# we only need the latest git commit
git:
  depth: 1
