language: go
go:
 - 1.8.x
 - 1.9.x
 - 1.10.x

env:
- TEST_SUITE="lint"
- TEST_SUITE="unit-test"
- TEST_SUITE="integ-test"

sudo: false

# Use trusty for postgres 9.5 support
dist: trusty

addons:
  postgresql: "9.5"

services:
  - postgresql

cache:
  directories:
    - .downloads

install:
 - go get github.com/constabulary/gb/...

script:
 - ./scripts/travis-test.sh

# we only need the latest git commit
git:
  depth: 1
