language: go
go:
 - 1.8
install:
 - go get github.com/constabulary/gb/...
 - go get github.com/golang/lint/golint
 - go get github.com/fzipp/gocyclo

script: gb build github.com/matrix-org/dendrite/roomserver/roomserver && ./hooks/pre-commit

notifications:
    webhooks:
        urls:
            - "https://scalar.vector.im/api/neb/services/hooks/dHJhdmlzLWNpLyU0MGtlZ2FuJTNBbWF0cml4Lm9yZy8lMjFhWmthbkFuV0VkeGNSSVFrV24lM0FtYXRyaXgub3Jn"
        on_success: change  # always|never|change
        on_failure: always
        on_start: never

