version: "3.4"
services:
    monolith:
        hostname: monolith
        image: matrixdotorg/dendrite:monolith
        command: [
            "--config=dendrite.yaml",
            "--tls-cert=server.crt",
            "--tls-key=server.key"
        ]
        volumes:
            - ./config:/etc/dendrite
        networks:
            - internal

networks:
  internal:
    attachable: true
